import { MenuItem, Category } from "../types";

export const DEFAULT_CATEGORIES: Category[] = [
  { id: "main-course", name: "Main Course", createdAt: new Date(Date.now() - 7000).toISOString() },
  { id: "south-indian", name: "South Indian", createdAt: new Date(Date.now() - 6000).toISOString() },
  { id: "burgers-wraps", name: "Burgers & Wraps", createdAt: new Date(Date.now() - 5000).toISOString() },
  { id: "snacks", name: "Snacks", createdAt: new Date(Date.now() - 4000).toISOString() },
  { id: "mocktails-beverages", name: "Mocktails & Beverages", createdAt: new Date(Date.now() - 3000).toISOString() },
  { id: "desserts", name: "Desserts", createdAt: new Date(Date.now() - 2000).toISOString() },
  { id: "smoothies", name: "Smoothies", createdAt: new Date(Date.now() - 1000).toISOString() }
];

export const DEFAULT_MENU: MenuItem[] = [
  // MAIN COURSE (Indian)
  {
    id: "paneer-butter-masala-with-roti",
    name: "Paneer Butter Masala with Roti",
    description: "Rich, creamy tomato-butter gravy with soft paneer cubes, served with 2 hot butter rotis.",
    price: 245,
    category: "main-course",
    imageUrl: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Best Seller", "North Indian"],
    stockLevel: 15,
    veg: true,
    rating: 4.8,
    prepTime: 15
  },
  {
    id: "veg-biryani",
    name: "Veg Biryani",
    description: "Fragrant basmati rice cooked with assorted vegetables, aromatic spices, served with fresh raita.",
    price: 225,
    category: "main-course",
    imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Aromatic", "Spicy"],
    stockLevel: 10,
    veg: true,
    rating: 4.5,
    prepTime: 12
  },
  {
    id: "chicken-curry-with-rice",
    name: "Chicken Curry with Rice",
    description: "Homestyle chicken curry slow-cooked in a robust onion-tomato gravy, served with fluffy basmati rice.",
    price: 295,
    category: "main-course",
    imageUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["High Protein", "Spicy"],
    stockLevel: 12,
    veg: false,
    rating: 4.7,
    prepTime: 15
  },
  {
    id: "dal-tadka-with-rice",
    name: "Dal Tadka with Rice",
    description: "Yellow lentils tempered with ghee, cumin, garlic, and dried red chillies, served with steamed rice.",
    price: 185,
    category: "main-course",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsDtbHeD2bdDsgeLJT57yiMGpGUZBe0_EfmvbCGDP1gg&s=10",
    available: true,
    tags: ["Comfort Food", "Light"],
    stockLevel: 20,
    veg: true,
    rating: 4.4,
    prepTime: 8
  },
  {
    id: "egg-curry-with-rice",
    name: "Egg Curry with Rice",
    description: "Two hard-boiled eggs pan-fried and simmered in a warm masala gravy, served with basmati rice.",
    price: 215,
    category: "main-course",
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Eggitarian", "Popular"],
    stockLevel: 14,
    veg: false,
    rating: 4.3,
    prepTime: 10
  },

  // SOUTH INDIAN
  {
    id: "masala-dosa",
    name: "Masala Dosa",
    description: "Crispy fermented rice crepe stuffed with spiced potato mash, served with coconut chutney and hot sambar.",
    price: 125,
    category: "south-indian",
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Crispy", "All-Time Fav"],
    stockLevel: 25,
    veg: true,
    rating: 4.9,
    prepTime: 5
  },
  {
    id: "idli-sambar-2-pcs",
    name: "Idli Sambar (2 pcs)",
    description: "Soft, pillowy steamed rice cakes served with tangy mixed-vegetable sambar and coconut chutney.",
    price: 115,
    category: "south-indian",
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Healthy", "Light"],
    stockLevel: 30,
    veg: true,
    rating: 4.7,
    prepTime: 3
  },
  {
    id: "medu-vada",
    name: "Medu Vada",
    description: "Deep-fried black gram fritters, crispy outside and fluffy inside, flavored with peppercorns and curry leaves.",
    price: 120,
    category: "south-indian",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOyuPetiukQFHkZTZDUO6eC3nfO7Swl4FL0hhoNq-ZXw&s=10",
    available: true,
    tags: ["Crispy", "Snack"],
    stockLevel: 18,
    veg: true,
    rating: 4.5,
    prepTime: 5
  },

  // BURGERS & WRAPS
  {
    id: "classic-veg-burger",
    name: "Classic Veg Burger",
    description: "Crispy vegetable patty layered with fresh lettuce, sliced tomatoes, onions, and signature burger sauce.",
    price: 165,
    category: "burgers-wraps",
    imageUrl: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Kid-Friendly", "Classic"],
    stockLevel: 15,
    veg: true,
    rating: 4.4,
    prepTime: 7
  },
  {
    id: "chicken-burger",
    name: "Chicken Burger",
    description: "Crispy fried chicken breast fillet topped with creamy mayonnaise, lettuce, and crunchy pickles on a toasted bun.",
    price: 210,
    category: "burgers-wraps",
    imageUrl: "https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Crispy", "High Protein"],
    stockLevel: 12,
    veg: false,
    rating: 4.6,
    prepTime: 8
  },
  {
    id: "cheese-burst-burger",
    name: "Cheese Burst Burger",
    description: "Loaded double patty filled with a liquid cheese center, crisp veggies, and garlic aioli.",
    price: 195,
    category: "burgers-wraps",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Cheesy", "Gourmet"],
    stockLevel: 10,
    veg: true,
    rating: 4.7,
    prepTime: 9
  },
  {
    id: "grilled-sandwich",
    name: "Grilled Sandwich",
    description: "Toasted white bread filled with spicy green chutney, sliced potatoes, cucumbers, onions, and melted cheese.",
    price: 155,
    category: "burgers-wraps",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYUUveT4_lyoaLpighy0BQpRrKPHmOF-1d_lHGtCwIXA&s=10",
    available: true,
    tags: ["Quick Bite", "Cheesy"],
    stockLevel: 20,
    veg: true,
    rating: 4.5,
    prepTime: 5
  },
  {
    id: "chicken-wrap",
    name: "Chicken Wrap",
    description: "Spiced grilled chicken strips, crunchy bell peppers, onions, and mint mayo encased in a soft flatbread.",
    price: 225,
    category: "burgers-wraps",
    imageUrl: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Protein Packed", "Tangy"],
    stockLevel: 10,
    veg: false,
    rating: 4.6,
    prepTime: 7
  },

  // SNACKS
  {
    id: "samosa-2-pcs",
    name: "Samosa (2 pcs)",
    description: "Crispy flaky golden pastry shells filled with a spiced potato and green peas mash.",
    price: 85,
    category: "snacks",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlxz7QeU8_nrfo4CKH-7FkOry6oSK5D9oqIrkZiMjEBg&s=10",
    available: true,
    tags: ["Legendary", "Street Food"],
    stockLevel: 40,
    veg: true,
    rating: 4.8,
    prepTime: 3
  },
  {
    id: "vada-pav",
    name: "Vada Pav",
    description: "Classic Mumbai street food: spiced potato fritter sandwiched inside a soft bun with dry garlic chutney.",
    price: 90,
    category: "snacks",
    imageUrl: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Mumbai Style", "Fiery"],
    stockLevel: 30,
    veg: true,
    rating: 4.7,
    prepTime: 4
  },
  {
    id: "aloo-tikki",
    name: "Aloo Tikki",
    description: "Golden-fried pan-crisped mashed potato patties served with sweet dahi, tamarind, and green chutneys.",
    price: 95,
    category: "snacks",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQX-L5hKl96iC2tfQSZVFzQLp2Vj1C1BSybdA9pbLG3xg&s=10",
    available: true,
    tags: ["Chaat", "Spiced"],
    stockLevel: 25,
    veg: true,
    rating: 4.5,
    prepTime: 5
  },
  {
    id: "golden-fries",
    name: "Golden Fries",
    description: "Classic potato fries crisped to perfection, tossed in simple sea salt or spicy peri-peri dust.",
    price: 135,
    category: "snacks",
    imageUrl: "https://images.unsplash.com/photo-1576107232684-1279f390859f?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Crispy", "All-Time Fav"],
    stockLevel: 35,
    veg: true,
    rating: 4.4,
    prepTime: 4
  },
  {
    id: "veg-cutlet",
    name: "Veg Cutlet",
    description: "Crispy heart-shaped deep fried cutlets made of carrots, potatoes, beans, and peas coated in breadcrumbs.",
    price: 115,
    category: "snacks",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgltyLMbUNGh9C6Z7B5ymbfTIflDJl09zAPEJyrsNHFw&s=10",
    available: true,
    tags: ["Teatime Special", "Crispy"],
    stockLevel: 15,
    veg: true,
    rating: 4.3,
    prepTime: 5
  },
  {
    id: "chicken-65",
    name: "Chicken 65",
    description: "Deep-fried spicy chicken chunks tempered with curry leaves, yogurt, and dry red chillies.",
    price: 210,
    category: "snacks",
    imageUrl: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Spicy", "Southern Star"],
    stockLevel: 12,
    veg: false,
    rating: 4.8,
    prepTime: 8
  },
  {
    id: "loaded-nachos",
    name: "Loaded Nachos",
    description: "Tortilla chips loaded with warm liquid cheese sauce, refried beans, sour cream, and jalapenos.",
    price: 175,
    category: "snacks",
    imageUrl: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["To Share", "Cheesy"],
    stockLevel: 18,
    veg: true,
    rating: 4.5,
    prepTime: 6
  },
  {
    id: "onion-rings",
    name: "Onion Rings",
    description: "Thick-cut sweet onion rings dipped in batter, coated in crunchy panko crumbs, and golden-fried.",
    price: 135,
    category: "snacks",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVe-U630Mbiv-ZQ8kB2ZbNOUM3gSk2FQPsa-IeczoH9Q&s=10",
    available: true,
    tags: ["Crunchy", "Sides"],
    stockLevel: 20,
    veg: true,
    rating: 4.2,
    prepTime: 5
  },
  {
    id: "chicken-popcorn",
    name: "Chicken Popcorn",
    description: "Bite-sized tender boneless chicken nuggets coated in seasoned flour, fried to a crackling crisp.",
    price: 195,
    category: "snacks",
    imageUrl: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Munchies", "Crispy"],
    stockLevel: 15,
    veg: false,
    rating: 4.6,
    prepTime: 6
  },
  {
    id: "garlic-bread",
    name: "Garlic Bread",
    description: "Three toasted baguette slices infused with aromatic garlic butter, herbs, and bubbly mozzarella.",
    price: 145,
    category: "snacks",
    imageUrl: "https://images.unsplash.com/photo-1544982503-9f984c14501a?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Cheesy", "Herbed"],
    stockLevel: 22,
    veg: true,
    rating: 4.6,
    prepTime: 5
  },

  // MOCKTAILS & BEVERAGES
  {
    id: "masala-chai",
    name: "Masala Chai",
    description: "Strong brewed black tea simmered with fresh milk, crushed ginger, cardamom, cloves, and cinnamon.",
    price: 65,
    category: "mocktails-beverages",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgfFTDNY-rVWE-S_eZRbtZspWN9u9KvMGG6WCxeatL2g&s=10",
    available: true,
    tags: ["Elixir", "Hot"],
    stockLevel: 100,
    veg: true,
    rating: 4.9,
    prepTime: 3
  },
  {
    id: "filter-coffee",
    name: "Filter Coffee",
    description: "Traditional South Indian frothy chicory coffee brewed in a brass filter, served hot in a tumbler.",
    price: 75,
    category: "mocktails-beverages",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTIVYqi5-oKrrCMXyCsgQl_txknwHC1uLaVxLsy4gutnRhsnhmRSrFyK4I&s=10",
    available: true,
    tags: ["Frothy", "Aromatic"],
    stockLevel: 80,
    veg: true,
    rating: 4.8,
    prepTime: 3
  },
  {
    id: "cold-coffee",
    name: "Cold Coffee",
    description: "Chilled espresso blended with thick creamy milk, sugar, and a scoop of vanilla ice cream.",
    price: 135,
    category: "mocktails-beverages",
    imageUrl: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Iced", "Sweet"],
    stockLevel: 40,
    veg: true,
    rating: 4.5,
    prepTime: 4
  },
  {
    id: "lassi-sweet-salted",
    name: "Lassi (Sweet/Salted)",
    description: "Rich, creamy churned Punjabi yogurt drink topped with a thick dollop of malai.",
    price: 115,
    category: "mocktails-beverages",
    imageUrl: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Thick", "Refreshing"],
    stockLevel: 30,
    veg: true,
    rating: 4.7,
    prepTime: 3
  },
  {
    id: "buttermilk",
    name: "Buttermilk",
    description: "Spiced watered-down yogurt infused with crushed ginger, green chillies, coriander, and roasted cumin.",
    price: 75,
    category: "mocktails-beverages",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtN_R5chzTOpuJzrXXDJ-Zg1z_t4UjHxl1NuFdatobRQ&s=10",
    available: true,
    tags: ["Digestive", "Chilled"],
    stockLevel: 35,
    veg: true,
    rating: 4.6,
    prepTime: 2
  },
  {
    id: "virgin-mojito",
    name: "Virgin Mojito",
    description: "Thirst-quenching summer mocktail with crushed fresh mint leaves, lime wedges, sugar syrup, and fizzy soda.",
    price: 145,
    category: "mocktails-beverages",
    imageUrl: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Minty", "Chilled"],
    stockLevel: 25,
    veg: true,
    rating: 4.5,
    prepTime: 4
  },
  {
    id: "blue-lagoon",
    name: "Blue Lagoon",
    description: "Stunning neon-blue beverage with Blue Curacao syrup, fresh lemon juice, and chilled Sprite.",
    price: 165,
    category: "mocktails-beverages",
    imageUrl: "https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Exotic", "Neon"],
    stockLevel: 20,
    veg: true,
    rating: 4.6,
    prepTime: 4
  },
  {
    id: "watermelon-cooler",
    name: "Watermelon Cooler",
    description: "Freshly cold-pressed sweet seedless watermelon juice accented with mint sprigs and black salt.",
    price: 135,
    category: "mocktails-beverages",
    imageUrl: "https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Hydrating", "No Sugar"],
    stockLevel: 22,
    veg: true,
    rating: 4.4,
    prepTime: 3
  },
  {
    id: "fresh-lime-soda",
    name: "Fresh Lime Soda",
    description: "Zesty freshly-squeezed lime juice with carbonated water, with your choice of sweet, salted, or mixed flavor.",
    price: 95,
    category: "mocktails-beverages",
    imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Citrus", "Fizzy"],
    stockLevel: 50,
    veg: true,
    rating: 4.5,
    prepTime: 3
  },
  {
    id: "oreo-shake",
    name: "Oreo Shake",
    description: "Decadent milkshake blended with Oreo biscuits, rich vanilla cream, dark chocolate syrup, and cookies on top.",
    price: 175,
    category: "mocktails-beverages",
    imageUrl: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&q=80&w=800",
    available: true,
    tags: ["Dessert", "Thick"],
    stockLevel: 15,
    veg: true,
    rating: 4.8,
    prepTime: 5
  },
  {
    id: "chocolate-milkshake",
    name: "Chocolate Milkshake",
    description: "Thick and luscious chocolate milkshake blended with cocoa powder, milk, sugar, and vanilla ice cream.",
    price: 165,
    category: "mocktails-beverages",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSihODXHN0rhLqgGC5YTOc_Mj5XzsmGXbFOSlciVdh5tg&s=10",
    available: true,
    tags: ["Classic", "Rich"],
    stockLevel: 18,
    veg: true,
    rating: 4.7,
    prepTime: 5
  },
  // DESSERTS
  {
    id: "chocolate-lava-cake",
    name: "Chocolate Lava Cake",
    description: "Decadent warm chocolate cake with a gooey liquid chocolate center, served with a scoop of vanilla bean ice cream.",
    price: 195,
    category: "desserts",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJArAYL4lxox4ywY-TaJE82BiQDiiYBTR1-v-XeldIrQ&s=10",
    available: true,
    tags: ["Signature", "Warm & Sweet"],
    stockLevel: 12,
    veg: true,
    rating: 4.9,
    prepTime: 6
  },
  {
    id: "sizzling-brownie",
    name: "Sizzling Brownie",
    description: "Fudgy chocolate brownie served on a hot sizzling iron plate, topped with vanilla ice cream and warm chocolate fudge drizzle.",
    price: 245,
    category: "desserts",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkeHdV_SUVdiRHAFnzZJDN2N2Ak8mUoGdwegECHq9nLw&s=10",
    available: true,
    tags: ["Chef's Special", "Showstopper"],
    stockLevel: 10,
    veg: true,
    rating: 4.9,
    prepTime: 8
  },
  {
    id: "gulab-jamun",
    name: "Gulab Jamun (2 pcs)",
    description: "Traditional milk-solid dumplings fried and soaked in cardamom-flavored warm sugar syrup.",
    price: 115,
    category: "desserts",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWzcBFRXk1FMm7kbaVYJMKWMPhmErpWcx0ghydyJ2U2g&s=10",
    available: true,
    tags: ["Classic", "Sweet"],
    stockLevel: 25,
    veg: true,
    rating: 4.8,
    prepTime: 3
  },
  // SMOOTHIES
  {
    id: "strawberry-banana-smoothie",
    name: "Strawberry Banana Smoothie",
    description: "A thick blend of fresh strawberries, ripe bananas, Greek yogurt, and a touch of organic honey.",
    price: 175,
    category: "smoothies",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScasw5VjEq-5HNXO9LVJjrucAeHqgwdj7D-tER52C_wA&s=10",
    available: true,
    tags: ["Healthy", "High Fiber"],
    stockLevel: 20,
    veg: true,
    rating: 4.6,
    prepTime: 4
  },
  {
    id: "mango-mastani-smoothie",
    name: "Mango Mastani Smoothie",
    description: "Thick luscious mango pulp smoothie blended with milk, topped with a scoop of vanilla ice cream, chopped nuts, and cherries.",
    price: 185,
    category: "smoothies",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiygkwGMc4PnyEGLVrqThZK4HfwQJQYj304rQG8F3nAQ&s=10",
    available: true,
    tags: ["Seasonal Special", "Rich"],
    stockLevel: 15,
    veg: true,
    rating: 4.8,
    prepTime: 5
  },
  {
    id: "green-detox-smoothie",
    name: "Green Detox Smoothie",
    description: "Nutrient-dense blend of baby spinach, green apples, cucumbers, ginger, lime juice, and coconut water.",
    price: 175,
    category: "smoothies",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIDfbKpRtSFGX2sPl8EzV1qCJy5XaVwxtUiBkJ1cq-Pg&s=10",
    available: true,
    tags: ["Superfood", "Detox"],
    stockLevel: 18,
    veg: true,
    rating: 4.4,
    prepTime: 4
  }
];
